### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Saltb0xApps** [zhvng/open-musiclm#1]
Hi there, I want to start off by saying amazing work replicating MusicLM so quickly!

I'm trying to get this to run on my local device, but it seems like that involves downloading the 100Gb fma_large dataset, followed by training all the various stages.
Would it be possible for you to upload the pretrained models in the results folders so everyone can try this out quickly?

**Comment by zhvng** [comment]
Hey! This repo is a work in progress and I'm still verifying that the implementation works. Will upload checkpoints once I am able to train it and obtain preliminary results.
