### ISSUE TITLE
Discord invite link expired

### ISSUE THREAD

**Issue by jlalmes** [zhvng/open-musiclm#15]
Morning @zhvng, I'm really keen to hear the samples of your early results.

Seems the invite link to your Discord has expired ([https://discord.gg/jN8jADShX5](https://discord.gg/jN8jADShX5)). Could you update it? Many thanks.

**Comment by zhvng** [comment]
Oh that's weird, it's not showing up as expired to me. Try this one instead? https://discord.gg/XZVSFFHwCA

**Comment by lvZic** [comment]
> Oh that's weird, it's not showing up as expired to me. Try this one instead? https://discord.gg/XZVSFFHwCA

expired again.

**Comment by Delamcode** [comment]
You were probably banned. Working fine for me
