### ISSUE TITLE
Ran the reasoning for hours without stopping

### ISSUE THREAD

**Issue by cendelian** [zhvng/open-musiclm#28]
when i run infer_top_match.py , Running for a few hours has not ended, how to control the length of generation?

![企业微信截图_16911461085706](https://github.com/zhvng/open-musiclm/assets/50360389/a60d7d91-1653-4ab9-b5c5-8e1dccd12d5a)
请问怎么结束生成？运行几个小时依然没有结束生成，没有产生结果

**Comment by JunZhan2000** [comment]
遇到了同样的问题，请问你解决了吗
