### ISSUE TITLE
Hubert args normalization

### ISSUE THREAD

**Issue by LWprogramming** [zhvng/open-musiclm#7]
I looked at the [MERT example](https://huggingface.co/m-a-p/MERT-v0) and noticed that it's actually preprocessing the input. The code looks really convoluted but in the case of batch size 1, the net effect is that it's [normalizing](https://github.com/huggingface/transformers/blob/f7329751fe5c43365751951502c00df5a4654359/src/transformers/models/wav2vec2/feature_extraction_wav2vec2.py#L81) things to have zero mean and unit variance instead of [passing it in directly](https://github.com/zhvng/open-musiclm/blob/03e4d6f45e4041899d5250e2f89548aa5592f7bd/open_musiclm/hf_hubert_kmeans.py#L71).

Note that you can use the `processor` provided in the example if you want, but I decided not to for my case because my `wav_input` is already in CUDA and `transformers` forces everything into numpy and therefore CPU 😞 , resulting in expensive copies as you move data back and forth. Wasn't sure which one you've got here :))

**Comment by zhvng** [comment]
hey, thanks for taking a look at the code! The input is normalized to zero mean unit variance when loading the data [here](https://github.com/zhvng/open-musiclm/blob/main/open_musiclm/data.py#L99). The `normalize` argument is set when initializing the datasets in [trainer](https://github.com/zhvng/open-musiclm/blob/main/open_musiclm/trainer.py#L160). This will normalize the data before it is cropped. 

Alternatively we could normalize the cropped input right before passing it into MERT. Not sure which would be better, but normalizing it in the beginning made more sense to me.
